name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      REACT_APP_SKIP_INPUT: false

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Fetch Cypress deps
        run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Build enviroment
        run: npm install
      - name: Run tests
        run: npm test
      - name: Checking coverage
        run: npm test -- --coverage --watchAll=false
      - name: Starting server
        run: npm start &
      - name: Cypress
        run: npm run cypress:run
      - name: Upload Cypress
        if: failure()
        uses: actions/upload-artifact@v2.2.0
        with:
          name: test-videos
          path: cypress/videos
      - name: Upload coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
