name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
      - name: Build enviroment
        run: npm install
      - name: Run tests
        run: npm test
      - name: Checking coverage
        run: npm test -- --coverage --watchAll=false
      - name: Starting server
        run: npm start & wait-on http://localhost:3000
      - name: Cypress.io
        uses: cypress-io/github-action@v1.16.1
      - name: Upload coverage
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
